### ISSUE TITLE
What is wrong with you!

### ISSUE THREAD

**Issue by CSEKU160212** [rakib06/rakib06#1]
I was curious about the repo "rakib06". I thought I am gonna learn something new from this repo. But you created a repo that has only some info about you. 

![download](https://user-images.githubusercontent.com/23745270/130353360-7db968f8-fbd2-4080-9b97-ef7c2e4eec08.jpeg)

**Comment by rakib06** [comment]
Try to make a repo using your git username..
You will see a message that it's a special kind of repo for showing info about you..
![image](https://user-images.githubusercontent.com/34921424/130356177-70d23af1-6338-4d8e-9cf4-9728dec1c97d.png)

**Comment by CSEKU160212** [comment]
Got it

**Comment by rakib06** [comment]
Thank you
